<template>
  <div id="app">
    <draggable
      class="icons"
      v-model="icons"
      group="icons"
      handle=".app__icon"
      :delay="500"
      :forceFallback="true"
      @choose="iconSelected"
      @unchoose="iconUnselected"
      @start="drag = true"
      @end="drag = false"
    >
      <Icon
        v-for="icon in icons"
        :name="icon.name"
        :file="icon.file"
        :key="icon.name"
        :selectedIcon="selectedIcon"
      />
    </draggable>
  </div>
</template>

<script>
import draggable from "vuedraggable";
import Icon from "./components/Icon";

export default {
  name: "App",
  components: { draggable, Icon },
  data() {
    return {
      icons: [
        { name: "Adobe", file: "adobe.png" },
        { name: "Android", file: "android.png" },
        { name: "App Store", file: "app-store.png" },
        { name: "Bing", file: "bing.png" },
        { name: "Chrome", file: "chrome.png" },
        { name: "Documents", file: "documents.png" },
        { name: "Drive", file: "drive.png" },
        { name: "Dropbox", file: "dropbox.png" },
        { name: "Excel", file: "excel.png" },
        { name: "Firefox", file: "firefox.png" },
        { name: "Gmail", file: "gmail.png" },
        { name: "Google Maps", file: "google-maps.png" },
        { name: "iCloud", file: "icloud.png" },
        { name: "IE", file: "ie.png" },
        { name: "Linux", file: "linux.png" },
        { name: "Outlook", file: "outlook.png" },
        { name: "Photoshop", file: "photoshop.png" },
        { name: "Powerpoint", file: "powerpoint.png" },
        { name: "Safari", file: "safari.png" },
        { name: "Windows", file: "windows.png" }
      ],
      selectedIcon: false
    };
  },
  methods: {
    iconSelected: function(e) {
      console.log("chosen");
      const selectedIconIndex = e.oldIndex;
      this.selectedIcon = {
        name: this.icons[selectedIconIndex].name,
        file: this.icons[selectedIconIndex].file
      };
    },
    iconUnselected: function() {
      console.log("unchosen");
      this.selectedIcon = false;
    }
  }
};
</script>

<style>
body {
  font-family: "Lato", sans-serif;
  margin: 0;
  color: #333;
  background-image: repeating-linear-gradient(
    to right,
    whitesmoke,
    whitesmoke 5px,
    rgb(241, 241, 241) 5px,
    rgb(241, 241, 241) 10px
  );
}

.app {
  display: flex;
  flex-direction: column;
  align-items: center;
  justify-content: center;
  padding: 10px;
  -webkit-user-select: none;
}

@-moz-document url-prefix() {
    .app {
        -webkit-user-select: initial;
    }
}

.icons {
  width: 1000px;
  max-width: 100%;
  margin: auto;
  display: grid;
  grid-template-columns: 1fr 1fr 1fr 1fr 1fr 1fr;
}

.app__label-txt {
  margin: 0;
}

.app__icon {
  width: 80px;
  padding: 10px;
  border-radius: 5px;
  cursor: pointer;
  transition: background-color 0.1s;
  -webkit-touch-callout: none;
}

.app__icon.selecting {
  background-color: #ededed;
  -webkit-animation: vibrate-3 0.8s linear infinite both;
  animation: vibrate-3 0.8s linear infinite both;
}
.app__icon.selected {
  background-color: #dedede;
}

@media (max-width: 999px) {
  .icons {
    grid-template-columns: 1fr 1fr 1fr 1fr;
  }
}
@media (max-width: 499px) {
  .icons {
    grid-template-columns: 1fr 1fr;
  }
}

/* ----------------------------------------------
 * Generated by Animista on 2020-2-16 17:28:28
 * Licensed under FreeBSD License.
 * See http://animista.net/license for more info. 
 * w: http://animista.net, t: @cssanimista
 * ---------------------------------------------- */

@-webkit-keyframes vibrate-3 {
  0% {
    -webkit-transform: translate(0);
    transform: translate(0);
  }
  10% {
    -webkit-transform: translate(-2px, -2px);
    transform: translate(-2px, -2px);
  }
  20% {
    -webkit-transform: translate(2px, -2px);
    transform: translate(2px, -2px);
  }
  30% {
    -webkit-transform: translate(-2px, 2px);
    transform: translate(-2px, 2px);
  }
  40% {
    -webkit-transform: translate(2px, 2px);
    transform: translate(2px, 2px);
  }
  50% {
    -webkit-transform: translate(-2px, -2px);
    transform: translate(-2px, -2px);
  }
  60% {
    -webkit-transform: translate(2px, -2px);
    transform: translate(2px, -2px);
  }
  70% {
    -webkit-transform: translate(-2px, 2px);
    transform: translate(-2px, 2px);
  }
  80% {
    -webkit-transform: translate(-2px, -2px);
    transform: translate(-2px, -2px);
  }
  90% {
    -webkit-transform: translate(2px, -2px);
    transform: translate(2px, -2px);
  }
  100% {
    -webkit-transform: translate(0);
    transform: translate(0);
  }
}
@keyframes vibrate-3 {
  0% {
    -webkit-transform: translate(0);
    transform: translate(0);
  }
  10% {
    -webkit-transform: translate(-2px, -2px);
    transform: translate(-2px, -2px);
  }
  20% {
    -webkit-transform: translate(2px, -2px);
    transform: translate(2px, -2px);
  }
  30% {
    -webkit-transform: translate(-2px, 2px);
    transform: translate(-2px, 2px);
  }
  40% {
    -webkit-transform: translate(2px, 2px);
    transform: translate(2px, 2px);
  }
  50% {
    -webkit-transform: translate(-2px, -2px);
    transform: translate(-2px, -2px);
  }
  60% {
    -webkit-transform: translate(2px, -2px);
    transform: translate(2px, -2px);
  }
  70% {
    -webkit-transform: translate(-2px, 2px);
    transform: translate(-2px, 2px);
  }
  80% {
    -webkit-transform: translate(-2px, -2px);
    transform: translate(-2px, -2px);
  }
  90% {
    -webkit-transform: translate(2px, -2px);
    transform: translate(2px, -2px);
  }
  100% {
    -webkit-transform: translate(0);
    transform: translate(0);
  }
}
</style>
